
package menuutama;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.Koneksi;

/**
 *
 * @author Neubri
 */
public class DataPaket extends javax.swing.JPanel {
    //koneksi mysql 
    private Connection conn = new Koneksi().connect();
    private DialogTambahData dialog = new DialogTambahData(null, true);
    public DefaultTableModel tabmode;
    private String noId;
    
    /**
     * Creates new form NewJPanel
     */
    public DataPaket() {
        initComponents();
        updateDataTabel();
    }
    
    /**
     * mendapatkan Data Tabel dari database
     */
    protected void updateDataTabel(){
        Object[] Baris = {
            "Id Paket",
            "Nama Paket",
            "Jenis Menu",
            "Tingkat Vegetarian",
            "Jumlah Orang",
            "Menu Paket",
            "Harga Paket",
            "Jumlah Menu",
            "Tingkat Popularitas"
        };
        
        tabmode = new DefaultTableModel(null, Baris);
        tabelDataPaket.setModel(tabmode);

        String sql = "SELECT * FROM data_paket ORDER BY id_paket";
        
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String a = hasil.getString("id_paket");
                String b = hasil.getString("nama_paket");
                String c = hasil.getString("jenis_menu");
                String d = hasil.getString("tingkat_vegetarian");
                String e = hasil.getString("jumlah_orang");
                String f = hasil.getString("menu_paket");
                String g = hasil.getString("harga_paket");
                String h = hasil.getString("jumlah_menu");
                String i = hasil.getString("tingkat_popularitas");
                
                String[] data={a, b, c, d, e, f, g, h, i};
                tabmode.addRow(data);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
    /**
     * Mendapatkan Data dari Tabel
     */
    private void getDataTabel(){
        int bar = tabelDataPaket.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        String e = tabmode.getValueAt(bar, 4).toString();
        String f = tabmode.getValueAt(bar, 5).toString();
        String g = tabmode.getValueAt(bar, 6).toString();
        String h = tabmode.getValueAt(bar, 7).toString();
        String i = tabmode.getValueAt(bar, 8).toString();
        
        noId = a;
        dialog.setDataTabel(a, b, c, d, e, f, g, h, i);
    }
    
    protected void hapusDataPaket(){
        if(noId != null){
            int ok = JOptionPane.showConfirmDialog(null,"hapus","Konfirmasi Dialog",JOptionPane.YES_NO_OPTION);
            if(ok == 0){
                String sql = "DELETE FROM data_paket WHERE id_paket='"+noId+"'";
                try{
                    PreparedStatement stat = conn.prepareStatement(sql);
                    stat.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Data Berhasil diHapus ");
                    updateDataTabel();
                    noId=null;
                }catch(SQLException e){
                    JOptionPane.showMessageDialog(null,"Data Gagal diHapus " + e);
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "Pilih data yang ingin dihapus! ");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        judul = new javax.swing.JLabel();
        Panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDataPaket = new javax.swing.JTable();
        tombolTambah = new javax.swing.JButton();
        tombolEdit = new javax.swing.JButton();
        tombolHapus = new javax.swing.JButton();
        catatan = new javax.swing.JLabel();
        catatan2 = new javax.swing.JLabel();
        catatan1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 237, 192));

        judul.setBackground(new java.awt.Color(22, 65, 53));
        judul.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        judul.setForeground(new java.awt.Color(255, 237, 192));
        judul.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        judul.setText("  Data Paket Makanan");
        judul.setOpaque(true);

        Panel.setBackground(new java.awt.Color(255, 237, 192));

        tabelDataPaket.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tabelDataPaket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Paket", "Nama Paket", "Jenis Menu", "Tingkat Prioritas", "Jumlah Orang", "Menu Paket", "Harga Paket", "Jumlah Menu", "Tingkat Vegetarian"
            }
        ));
        tabelDataPaket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDataPaketMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelDataPaket);

        tombolTambah.setBackground(new java.awt.Color(22, 65, 53));
        tombolTambah.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tombolTambah.setForeground(new java.awt.Color(255, 237, 192));
        tombolTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Icon Tambah Small.png"))); // NOI18N
        tombolTambah.setText("TAMBAH");
        tombolTambah.setBorder(null);
        tombolTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolTambahActionPerformed(evt);
            }
        });

        tombolEdit.setBackground(new java.awt.Color(22, 65, 53));
        tombolEdit.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tombolEdit.setForeground(new java.awt.Color(255, 237, 192));
        tombolEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Icon Ubah Small.png"))); // NOI18N
        tombolEdit.setText("UBAH");
        tombolEdit.setBorder(null);
        tombolEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolEditActionPerformed(evt);
            }
        });

        tombolHapus.setBackground(new java.awt.Color(22, 65, 53));
        tombolHapus.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tombolHapus.setForeground(new java.awt.Color(255, 237, 192));
        tombolHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Icon Hapus Small.png"))); // NOI18N
        tombolHapus.setText("HAPUS");
        tombolHapus.setBorder(null);
        tombolHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolHapusActionPerformed(evt);
            }
        });

        catatan.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        catatan.setText("Catatan : Edit/Hapus data paket makanan, klik data pada tabel terlebih dahulu");

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tombolTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tombolEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tombolHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
                        .addGroup(PanelLayout.createSequentialGroup()
                            .addComponent(catatan, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 384, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombolTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tombolEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tombolHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(382, Short.MAX_VALUE))
            .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelLayout.createSequentialGroup()
                    .addGap(61, 61, 61)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(catatan)
                    .addGap(0, 147, Short.MAX_VALUE)))
        );

        catatan2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        catatan2.setText("Jika harga paket 6 - 9 Juta cukup input 2 angka awal harga paket");

        catatan1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        catatan1.setText("Jika harga paket diatas 10 Juta (puluhan) cukup input 3 angka awal harga paket");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(judul, javax.swing.GroupLayout.DEFAULT_SIZE, 853, Short.MAX_VALUE)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(catatan2)
                    .addComponent(catatan1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(catatan2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(catatan1)
                .addGap(195, 195, 195))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tombolHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolHapusActionPerformed
        // TODO add your handling code here:
        hapusDataPaket();
    }//GEN-LAST:event_tombolHapusActionPerformed

    private void tombolEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolEditActionPerformed
        // TODO add your handling code here:
        if(noId != null){
            dialog.show();
            updateDataTabel();
            noId=null;
        }else{
            JOptionPane.showMessageDialog(null, "Pilih data yang ingin diubah!");
        }
    }//GEN-LAST:event_tombolEditActionPerformed

    private void tombolTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolTambahActionPerformed
        // TODO add your handling code here:
            dialog.kosong();
            dialog.show();
            updateDataTabel();  
            noId=null;
    }//GEN-LAST:event_tombolTambahActionPerformed

    private void tabelDataPaketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDataPaketMouseClicked
        // TODO add your handling code here:
        getDataTabel();
    }//GEN-LAST:event_tabelDataPaketMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel catatan;
    private javax.swing.JLabel catatan1;
    private javax.swing.JLabel catatan2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel judul;
    private javax.swing.JTable tabelDataPaket;
    private javax.swing.JButton tombolEdit;
    private javax.swing.JButton tombolHapus;
    private javax.swing.JButton tombolTambah;
    // End of variables declaration//GEN-END:variables
}
